### ISSUE TITLE
letsencrypt yields ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by tylercal** [sprockteam/easy-ubnt#1]
With a vanilla installation of the unifi controller (5.6.42) I can connect with the self-signed cert. After running the letsencrypt setup, upon restart of the controller I see

`<launcher> WARN  JSSESocketFactory - None of the SSL protocols specified are supported by the SSL engine : [+TLSv1.1, +TLSv1.2, +SSLv2Hello]`

in `server.log` twice. APs seem to continue to inform to the controller, but I cannot access from any browser as I get `ERR_SSL_VERSION_OR_CIPHER_MISMATCH`

`keytool -list -v -keystore /var/lib/keystore -storepass aircontrolenterprise` shows an entry with Let's Encrypt as the issuer.

**Comment by tylercal** [comment]
so commenting out
```properties
unifi.https.ciphers=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_EMPTY_RENEGOTIATION_INFO_SCSVF
unifi.https.sslEnabledProtocols=+TLSv1.1,+TLSv1.2,+SSLv2Hello
```

in `/var/lib/unifi/system.properties` actually seems to have resolved the issue. Not sure what's unique about my setup, but would be good to adjust the script to handle this situation. Also, I'm not sure that it wouldn't go back to the config that doesn't work the next time the cert renews.

**Comment by sprocktech-dev** [comment]
Yes, I was going to suggest that as a troubleshooting step. Thanks for reporting that worked, I’ll adjust the script.
